
runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "opencollab-bucket"

handlers:
- url: /
  static_files: dist/open-collab/index.html
  upload: dist/open-collab/index.html

- url: /
  static_dir: dist/open-collab 
